@startuml
title 시퀀스 다이어그램
actor Client as C
participant Server as S
loop M times
    loop N times
        C -> C: 로직 수행
    end
end
alt Case 1
        C -[#0000FF]> S: <font color="#0000FF"> API-1 요청 
        activate S
        S -[#FF0000]X C: <b><font color="#FF0000"> API-1 응답 실패
        deactivate S
else Case 2
    C -> S: API-2 요청
    activate S
    loop N times
        S -> S: 로직 수행
    end
    S -> C: API-1 응답
    deactivate S
end
@enduml