@startuml
header 청약
footer Voice On CPaaS
title 소프트폰 PC 부가상품 해지 청약
actor customer as C #fffb00ff
participant portal as P #00ddffff
participant biznaru as B #00ddffff
participant kos as K #00ddffff
participant ktps as KP #00ddffff
participant centrex as CT #00ddffff
participant voice as V #00ddffff

C -> P: 가입된 부가상품 목록에서 해지 할 목록 선택

P -> B: 가입된 부가상품 해지 요청(**<color #red>INF-BIZNARU-430</color>**)
B -> K: 부가상품 해지 요청
K -> K: 부가상품 해지 처리

alt <color #0000FF>부가상품 해지 성공 시</color>

par <color #89c423fa>부가상품 해지 결과</color>
K --> B: 부가상품 해지 결과
B --> P: 부가상품 해지 결과
P -> P: 부가상품 관련 정보 삭제
note left P #ff8000ff
    부가상품가입정보,
    부가상품+기업전화번호 매핑 정보
    가입전화번호+ID,PW 매칭 정보
end note
P --> C: 부가상품 해지 셩공 결과 Noti.
else <color #89c423fa>부가상품 해지 정보 연동</color>
K -> KP: 부가상품 해지 정보
KP -> CT: 부가상품 해지 정보
CT -> V: 부가상품 해지 정보
end

else <color #FF0000>부가상품 청약 실패 시</color>
K --> B: 부가상품 해지 결과
B --> P: 부가상품 해지 결과
P --> C: 부가상품 해지 실패 결과 Noti.
end

@enduml