@startuml
header 청약
footer Voice On CPaaS
title 통화레코딩 부가상품 신규 청약
actor customer as C #fffb00ff
participant portal as P #00ddffff
participant biznaru as B #00ddffff
participant kos as K #00ddffff
participant ktps as KP #00ddffff
participant centrex as CT #00ddffff
participant voice as V #00ddffff
participant BizReco as BR #00ddffff

C -> P: 가입된 부가상품 목록에서 변경 할 \n 통화레코딩 부가상품 목록 선택
== 부가상품 변경 요청 ==
P -> P: 가입외 통화레코딩 부가상품 3개목록 중 1개 선택
note left P #ff8000ff
    1. 통화레코딩 1년
    2. 통화레코딩 3년
    3. AI통화레코딩 1년
    4. AI통화레코딩 3년
end note
P -> P: 레코딩 암호화 키 생성 및 \n 회선번호와 레코딩 암호화 키 매핑 저장
note left P #ff8000ff
    SEED 대칭키 암호화 방식으로 암호화키 생성
    선택 전화번호와 레코딩 암호화 키 매칭 처리
end note

P -> B: 선택된 부가상품으로 변경 청약 요청(**<color #red>INF-BIZNARU-423</color>**)
B -> K: 부가상품 변경 요청
K -> K: 부가상품 변경 처리

alt <color #0000FF>부가상품 변경 청약 성공 시</color>

par <color #89c423fa>부가상품 청약 결과</color>
K --> B: 부가상품 변경 청약 결과
B --> P: 부가상품 변경 청약 결과
P -> P: 부가상품 변경 청약 정보 저장
note left P #ff8000ff
    부가상품 가입정보,
    부가상품+기업전화번호 매핑 정보 변경 저장
    기업전화번호+암호화키 매핑 정보 변경 저장
end note
P --> C: 부가상품 변경 청약 성공 결과 Noti.
else <color #89c423fa>부가상품 청약 변경 정보 연동</color>
K -> KP: 부가상품 변경 청약 정보
KP -> CT: 부가상품 변경 청약 정보
CT -> V: 부가상품 변경 청약 정보
V -> BR: 부가상품 변경 청약 정보
end

else <color #FF0000>부가상품 청약 실패 시</color>
K --> B: 부가상품 변경 청약 결과
B --> P: 부가상품 변경 청약 결과
P --> C: 부가상품 변경 청약 실패 결과 Noti.
end

== 비고 ==
note left V #ff8000ff
    1. 통화레코딩과 AI통화레코딩 상품간의 변경 시 처리 절차 확인 필요
       -> KOS에서 상품변경으로 처리 하여 기존 상품 해지 없도록 진행 예정
    2. voice레코딩 암호화 키는 SEED 대칭키 암호화 방식으로 생성
    3. 통화레코딩(1년/3년), AI통화레코딩(1년/3년) 4개 상품간 호환 가능
    4. KOS오더에서 기존 지능망 상품과 배타 처리
    5. 통화레코딩은 전수 녹취, 부분 녹취 모두 가능하나 CPaaS에서는 전수녹취만 가능
       -> 현재 호 처리상 3시간 까지 한번에 녹취 가능 
end note

@enduml